[package]
name = "sharejs-clobber"
version = "0.1.0"
authors = ["nickbrowne <nickbrowne@users.noreply.github.com>"]

[dependencies]
curl = "0.4.12"
rand = "0.5.3"
serde_json = "1.0.27"
time = "0.1.40"
ws = "0.7.8"
